apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hulygram
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
spec:
  encryptedData:
    telegramApiId: {{.Values.hulygram.secrets.telegramApiId}}
    telegramApiHash: {{.Values.hulygram.secrets.telegramApiHash}}
    redisSecret: {{.Values.hulygram.secrets.redisSecret}}