apiVersion: apps/v1
kind: Deployment
metadata:
  name: hulypulse
spec:
  replicas: {{.Values.hulypulse.replicaCount}}
  selector:
    matchLabels:
      app: hulypulse
  template:
    metadata:
      labels:
        app: hulypulse
        tier: service
    spec:
      containers:
        - name: hulypulse
          image: hardcoreeng/{{.Values.hulypulse.imageName}}:{{coalesce .Values.hulypulse.imageTag .Values.baselineTag "latest"}}  
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8095
          env:
            - name: HULY_LOG
              value: {{ .Values.hulypulse.log  }}

            - name: HULY_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: huly-global
                  key: tokenSecret

            - name: HULY_HEARTBEAT_TIMEOUT
              value: "60"

            - name: HULY_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hulypulse
                  key: redisSecret
            {{- if eq .Values.hulypulse.redisMode "replication" }}
            - name: HULY_REDIS_MODE
              value: sentinel

            - name: HULY_REDIS_SERVICE
              value: {{ .Values.hulypulse.redisService }}

            - name: HULY_REDIS_URLS
              value: 'redis://hulypulse-redis-sentinel-0.hulypulse-redis-sentinel-headless:26379,redis://hulypulse-redis-sentinel-1.hulypulse-redis-sentinel-headless:26379,redis://hulypulse-redis-sentinel-2.hulypulse-redis-sentinel-headless:26379'
            {{- end }}

            {{- if eq .Values.hulypulse.redisMode "standalone" }}
            - name: HULY_REDIS_MODE
              value: direct

            - name: HULY_REDIS_URLS
              value: redis://hulypulse-redis:6379
            {{- end }}

