baselineTag: invalid
kafkaBootstrapServers: kafka:9092

otelMode: "off"
otelOtlpEndpoint: http://opentelemetry-collector:4317

secrets:
  tokenSecret: invalid
  databaseUrl: invalid

hulypulse:
  replicaCount: 1
  imageName: hulypulse
  imageTag: null
  log: debug
  redisMode: replication
  redisService: mymaster
  ingresHost: pulse.hc.engineering
  secrets:
    redisSecret: invalid

hulylake:
  replicaCount: 1
  imageName: hulylake
  imageTag: null
  ingresHost: lake.hc.engineering
  s3EndpointUrl: http://s3:80
  bucket: hulylake-staging
  log: debug
  secrets:
    accessKeyId: invalid
    secretAccessKey: invalid
  otelMode: null

hulykvs:
  replicaCount: 1
  imageName: hulykvs
  imageTag: null

hulygram:
  imageName: service_hulygram
  imageTag: latest
  pinToNode: null
  log: debug
  ingresHost: telegram.hc.engineering
  secrets:
    telegramApiId: invalid
    telegramApiHash: invalid
    redisSecret: invalid
  otelMode: null
  messageTearline: '[{first_name} {last_name} via https://huly.io]'

hulygun:
  imageName: hulygun
  imageTag: null
  log: debug
  otelMode: null
  
  