baselineTag: invalid

secrets:
  tokenSecret: invalid
  databaseUrl: invalid

hulypulse:
  replicaCount: 1
  imageName: hulypulse
  imageTag: null
  redisMode: replication
  ingresHost: pulse.hc.engineering
  secrets:
    redisSecret: invalid

hulylake:
  replicaCount: 1
  imageName: hulylake
  imageTag: null
  ingresHost: lake.hc.engineering
  s3EndpointUrl: http://192.168.100.100:80
  bucket: hulylake-staging
  secrets:
    accessKeyId: invalid
    secretAccessKey: invalid

hulykvs:
  replicaCount: 1
  imageName: hulykvs
  imageTag: null