apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hulylake
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
spec:
  encryptedData:
    accessKeyId: {{.Values.hulylake.secrets.accessKeyId}}
    secretAccessKey: {{.Values.hulylake.secrets.secretAccessKey}}