apiVersion: apps/v1
kind: Deployment
metadata:
  name: hulygun
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hulygun
  template:
    metadata:
      labels:
        app: hulygun
        tier: service
    spec:
      containers:
        - name: hulygun
          image: hardcoreeng/{{.Values.hulygun.imageName}}:{{coalesce .Values.hulygun.imageTag .Values.baselineTag "latest"}} 
          resources:
            limits:
              memory: '256M'
          imagePullPolicy: Always
          env:
            - name: HULY_LOG
              value: {{.Values.hulygun.log}}

            {{- include "otel.env" (merge (dict "otelMode" (coalesce .Values.hulygun.otelMode .Values.otelMode)) .) | nindent 12 }}

            - name: HULY_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: huly-global
                  key: tokenSecret
            - name: HULY_ACCOUNT_SERVICE
              value: http://account
            - name: HULY_EXTERNAL_REGIONS
              value: 'cf'
            - name: HULY_ACCOUNT_SERVICE_RATE_LIMIT
              value: '50'
            - name: HULY_KAFKA_BOOTSTRAP
              value: {{.Values.kafkaBootstrapServers}}
