apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: huly-global
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
spec:
  encryptedData:
    {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value }}
    {{- end }}